name: VzBot UserMods CI

# Loosely based on the CI build scripts from Voron (current) and ZeroG (previous)
# https://github.com/VoronDesign/VoronUsers/blob/master/.github/workflows/ci-build.yml
# https://github.com/ZeroGDesign/UserMods/blob/main/.github/workflows/ci-build.yml

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: ${{ github.head_ref }} 
      GIT_PR_BASE_BRANCH: ${{ github.base_ref	}}
      GIT_PULL_REQUEST: ${{ github.event.number }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache Folder
      id: cache-folder
      uses: actions/cache@v3
      with:
        path: ci_cache
        key: vzbot-usermods_ci
    - name: Setup Node / npm
      id: cache-npm
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        # cache-dependency-path: Only used to generate the cache name hash
        cache-dependency-path: '.github/workflows/ci-build.yml' 
    - name: Install npm scripts
      run: | 
        npm init -y
        npm install --global remark-cli remark-validate-links
    - name: Execute CI
      run: |
        git clone https://github.com/VoronDesign/GithubScripts.git .github_scripts
        /bin/bash ./.github_scripts/workflows/ci-build.sh
