name: VzBot UserMods CI

# Loosely based on the CI build scripts from Voron (current) and ZeroG (previous)
# https://github.com/VoronDesign/VoronUsers/blob/master/.github/workflows/ci-build.yml
# https://github.com/ZeroGDesign/UserMods/blob/main/.github/workflows/ci-build.yml

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        filter: |
          .github
    - name: Recall/deploy cache folder
      id: cache-folder
      uses: actions/cache@v3
      env:
          cache-name: ci-cache
      with:
        path: |
          **/node_modules
          ci_cache
          .github_scripts
        key: vzbot-usermods_${{ env.cache-name }}-${{ hashFiles('.github/workflows/ci-build.yml') }}
        restore-keys: |
          vzbot-usermods_${{ env.cache-name }}        
    - name: Setup Node.js / npm
      id: cache-npm
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        # cache-dependency-path: Only used to generate the cache name hash
        cache-dependency-path: '.github/workflows/ci-build.yml' 
    - name: Install npm scripts
      run: | 
        npm init -y
        npm install --global remark-cli remark-validate-links
    - name: Install CI scripts
      run: |
        git clone https://github.com/VoronDesign/GithubScripts.git .github_scripts
    
  run-script:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3          
    - name: Recall/deploy cache folder
      id: cache-folder
      uses: actions/cache@v3
      env:
          cache-name: ci-cache
      with:
        path: |
          **/node_modules
          ci_cache
          .github_scripts
        key: vzbot-usermods_${{ env.cache-name }}-${{ hashFiles('.github/workflows/ci-build.yml') }}
        restore-keys: |
          vzbot-usermods_${{ env.cache-name }}
    - name: Execute CI scripts
      run: |
        /bin/bash ./.github_scripts/workflows/ci-build.sh

